kind = "mobile"
previewPath = "/"
title = "Footwear"
version = "1.0.0"
id = "artifacts/footwear"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/" ]
localPort = 26057

[services.development]
run = "pnpm --filter @workspace/footwear run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/footwear", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/footwear", "run", "serve" ]

[services.env]
PORT = "26057"
BASE_PATH = "/"
